services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: httpsms
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_USER: dbusername
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 60s

  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - redis:/var/lib/redis
    restart: on-failure

  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    environment:
      APP_PORT: "8000"
    restart: unless-stopped
    networks:
      - dokploy-network

  web:
    build:
      context: ./web
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - dokploy-network

volumes:
  redis:
  postgres:

networks:
  dokploy-network:
    external: true
